# Generated by Django 5.1.2 on 2024-11-12 04:36

import grading.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grading", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="test_cases_file",
            field=models.FileField(
                default="", upload_to=grading.models.test_cases_directory_path
            ),
        ),
    ]
