# Generated by Django 5.1.2 on 2024-11-14 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grading", "0002_question_test_cases_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="qn_total_score",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
