# Generated by Django 5.1.2 on 2024-11-14 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grading", "0003_question_qn_total_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentsubmission",
            name="overall_score",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
