# Generated by Django 5.1.2 on 2024-11-14 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grading", "0004_studentsubmission_overall_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentsubmission",
            name="question_specific_total_score",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
