# in_built_variables = [
# {'abs': [int, float],'int': int,'float':'float','str':'str', 'all': 'bool', 'any': 'bool', 'ascii': 'str', 'bin': 'str', 'bool': 'bool', 'bytearray': 'bytearray', 'bytes': 'bytes', 'callable': 'bool', 'chr': 'str', 'classmethod': 'unknown', 'compile': 'unknown', 'complex': 'unknown', 'delattr': 'unknown', 'dict': 'dict', 'dir': 'list', 'divmod': 'tuple', 'enumerate': 'unknown', 'eval': 'unknown', 'exec': 'unknown', 'filter': 'unknown', 'format': 'str', 'frozenset': 'frozenset', 'getattr': 'unknown', 'globals': 'dict', 'hasattr': 'bool', 'hash': 'int', 'help': 'unknown', 'hex': 'str', 'id': 'int', 'input': 'str', 'isinstance': 'bool', 'issubclass': 'bool', 'iter': 'unknown', 'len': 'int', 'list': 'list', 'locals': 'dict', 'map': 'unknown', 'max': 'unknown', 'memoryview': 'unknown', 'min': 'unknown', 'next': 'unknown', 'object': 'unknown', 'oct': 'str', 'open': 'unknown', 'ord': 'int', 'pow': ['int', 'float'], 'print': 'unknown', 'property': 'unknown', 'range': 'unknown', 'repr': 'str', 'reversed': 'unknown', 'round': ['int', 'float'], 'set': 'set', 'setattr': 'unknown', 'slice': 'unknown', 'sorted': 'list', 'staticmethod': 'unknown', 'sum': ['int','float'] , 'super': 'unknown', 'tuple': 'tuple', 'type': 'unknown', 'vars': 'dict', 'zip': 'unknown'}
# ,{'capitalize': 'str', 'casefold': 'str', 'center': 'str', 'count': 'str', 'encode': 'str', 'endswith': 'str', 'expandtabs': 'str', 'find': 'str', 'format': 'str', 'format_map': 'str', 'index': 'str', 'isalnum': 'str', 'isalpha': 'str', 'isascii': 'str', 'isdecimal': 'str', 'isdigit': 'str', 'isidentifier': 'str', 'islower': 'str', 'isnumeric': 'str', 'isprintable': 'str', 'isspace': 'str', 'istitle': 'str', 'isupper': 'str', 'join': 'str', 'ljust': 'str', 'lower': 'str', 'lstrip': 'str', 'maketrans': 'str', 'partition': 'str', 'replace': 'str', 'rfind': 'str', 'rindex': 'str', 'rjust': 'str', 'rpartition': 'str', 'rsplit': 'str', 'rstrip': 'str', 'split': 'str', 'splitlines': 'str', 'startswith': 'str', 'strip': 'str', 'swapcase': 'str', 'title': 'str', 'translate': 'str', 'upper': 'str', 'zfill': 'str'}
# ]
from types import BuiltinFunctionType, BuiltinMethodType, MethodType, FunctionType, GeneratorType, CoroutineType, AsyncGeneratorType, CodeType, FrameType, TracebackType, GetSetDescriptorType, MemberDescriptorType, MappingProxyType, SimpleNamespace

severity = {
    'SYNTX001': {'Severity': 5, 'Marks': 0.5},
    'SYNTX002': {'Severity': 5, 'Marks': 0.5},
    'SYNTX003': {'Severity': 5, 'Marks': 0.5},
    'VARMGT001': {'Severity': 2, 'Marks': 0.2},
    'VARMGT002': {'Severity': 3, 'Marks': 0.3},
    'VARMGT003': {'Severity': 3, 'Marks': 0.3},
    'LOGIC001': {'Severity': 5, 'Marks': 0.5},
    'LOGIC002': {'Severity': 5, 'Marks': 0.5},
    'LOGIC003': {'Severity': 5, 'Marks': 0.5},
    'LOGIC004': {'Severity': 5, 'Marks': 0.5},
    'PERF001': {'Severity': 3, 'Marks': 0.3},
    'PERF002': {'Severity': 3, 'Marks': 0.3},
    'PERF003': {'Severity': 3, 'Marks': 0.3},
    'DATA001': {'Severity': 5, 'Marks': 0.5},
    'DATA002': {'Severity': 5, 'Marks': 0.5},
    'DATA003': {'Severity': 5, 'Marks': 0.5},
    'STYLE001': {'Severity': 2, 'Marks': 0.2},
    'STYLE002': {'Severity': 3, 'Marks': 0.3},
    'STYLE003': {'Severity': 3, 'Marks': 0.3},
    'OUTFMT001': {'Severity': 2, 'Marks': 0.2},
    'OUTFMT002': {'Severity': 2, 'Marks': 0.2},
    'OUTFMT003': {'Severity': 2, 'Marks': 0.2},
    'OUTFMT004': {'Severity': 2, 'Marks': 0.2},
    'ALGO001': {'Severity': 5, 'Marks': 0.5},
    'ALGO002': {'Severity': 3, 'Marks': 0.3},
    'ALGO003': {'Severity': 3, 'Marks': 0.3},
    'ERRHND001': {'Severity': 5, 'Marks': 0.5},
    'ERRHND002': {'Severity': 5, 'Marks': 0.5},
    'ERRHND003': {'Severity': 5, 'Marks': 0.5},
    'TEST001': {'Severity': 3, 'Marks': 0.3},
    'TEST002': {'Severity': 3, 'Marks': 0.3},
    'TEST003': {'Severity': 5, 'Marks': 0.5}
}

def get_severity(code):
    return severity[code]['Severity']

def get_marks(code):
    return severity[code]['Marks']


in_built_variables ={
        'abs': float,
        'int': int,
        'float': float,
        'str': str,
        'all': bool,
        'any': bool,
        'ascii': str,
        'bin': str,
        'bool': bool,
        'bytearray': bytearray,
        'bytes': bytes,
        'callable': bool,
        'chr': str,
        'classmethod': type,
        'compile': CodeType,
        'complex': complex,
        'delattr': None,
        'dict': dict,
        'dir': list,
        'divmod': tuple,
        'enumerate': enumerate,
        'eval': None,
        'exec': None,
        'filter': filter,
        'format': str,
        'frozenset': frozenset,
        'getattr': object,
        'globals': dict,
        'hasattr': bool,
        'hash': int,
        'help': None,
        'hex': str,
        'id': int,
        'input': str,
        'isinstance': bool,
        'issubclass': bool,
        'iter': iter,
        'len': int,
        'list': list,
        'locals': dict,
        'map': map,
        'max': object,
        'memoryview': memoryview,
        'min': object,
        'next': object,
        'object': object,
        'oct': str,
        'open': BuiltinFunctionType,
        'ord': int,
        'pow': float,
        'print': None,
        'property': property,
        'range': range,
        'repr': str,
        'reversed': reversed,
        'round': float,
        'set': set,
        'setattr': None,
        'slice': slice,
        'sorted': list,
        'staticmethod': staticmethod,
        'sum': float,
        'super': super,
        'tuple': tuple,
        'type': type,
        'vars': dict,
        'zip': zip,
        'capitalize': str,
        'casefold': str,
        'center': str,
        'count': int,
        'encode': bytes,
        'endswith': bool,
        'expandtabs': str,
        'find': int,
        'format': str,
        'format_map': str,
        'index': int,
        'isalnum': bool,
        'isalpha': bool,
        'isascii': bool,
        'isdecimal': bool,
        'isdigit': bool,
        'isidentifier': bool,
        'islower': bool,
        'isnumeric': bool,
        'isprintable': bool,
        'isspace': bool,
        'istitle': bool,
        'isupper': bool,
        'join': str,
        'ljust': str,
        'lower': str,
        'lstrip': str,
        'maketrans': dict,
        'partition': tuple,
        'replace': str,
        'rfind': int,
        'rindex': int,
        'rjust': str,
        'rpartition': tuple,
        'rsplit': list,
        'rstrip': str,
        'split': list,
        'splitlines': list,
        'startswith': bool,
        'strip': str,
        'swapcase': str,
        'title': str,
        'translate': str,
        'upper': str,
        'zfill': str
    }


# final_variables = {}
# for additional_dict in in_built_variables:
#     final_variables.update(additional_dict)

def get_final_in_built_variables():
    return in_built_variables